<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="gov.usgs.earthquake.product.io.ContentOutputThreadTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2019-08-05T22:07:29" hostname="igskcicgwsgm015" time="0.006">
  <properties/>
  <testcase name="testHandlerException" classname="gov.usgs.earthquake.product.io.ContentOutputThreadTest" time="0.006"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[WARNING	thread=1144	Exception delivering content 'null'
java.lang.Exception: for test
	at gov.usgs.earthquake.product.io.ContentOutputThreadTest$1.onContent(ContentOutputThreadTest.java:22)
	at gov.usgs.earthquake.product.io.ContentOutputThread.run(ContentOutputThread.java:34)
]]></system-err>
</testsuite>
